# -*- coding: utf-8 -*-
"""Sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iQcrwTKeS_U-F6yNwAZiBdMbzSkJtJyd
"""

import duckdb
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker

# Customer Revenue & Retention Analysis
# Olist Brazilian E-Commerce Dataset
# Olivia Bonnette

# ============================================================
# CELL 1: Setup
# ============================================================

# !pip install duckdb  # uncomment if needed in Colab

import duckdb
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import numpy as np

print("Packages loaded.")

# ============================================================
# CELL 2: Load data
# ============================================================

# Upload all 9 Olist CSV files using the folder icon on the left sidebar
# then run this cell

con = duckdb.connect()

con.execute("CREATE TABLE orders AS SELECT * FROM read_csv_auto('olist_orders_dataset.csv')")
con.execute("CREATE TABLE customers AS SELECT * FROM read_csv_auto('olist_customers_dataset.csv')")
con.execute("CREATE TABLE payments AS SELECT * FROM read_csv_auto('olist_order_payments_dataset.csv')")
con.execute("CREATE TABLE order_items AS SELECT * FROM read_csv_auto('olist_order_items_dataset.csv')")
con.execute("CREATE TABLE products AS SELECT * FROM read_csv_auto('olist_products_dataset.csv')")
con.execute("CREATE TABLE category_translation AS SELECT * FROM read_csv_auto('product_category_name_translation.csv')")

print("All tables loaded.")

# ============================================================
# CELL 3: Data validation
# ============================================================

print("Order status breakdown:")
print(con.execute("""
    SELECT order_status, COUNT(*) AS count
    FROM orders
    GROUP BY order_status
    ORDER BY count DESC
""").df())

print("\nNull counts in key fields:")
print(con.execute("""
    SELECT
        COUNT(*) - COUNT(order_purchase_timestamp)      AS null_purchase_date,
        COUNT(*) - COUNT(customer_id)                   AS null_customer_id,
        COUNT(*) - COUNT(order_delivered_customer_date) AS null_delivery_date
    FROM orders
""").df())

print("\nDate range:")
print(con.execute("""
    SELECT
        MIN(order_purchase_timestamp) AS earliest_order,
        MAX(order_purchase_timestamp) AS latest_order
    FROM orders
""").df())

# ============================================================
# CELL 4: Build base dataset (delivered orders only)
# ============================================================

# Restricting to delivered orders ensures revenue reflects completed
# transactions only, not cancellations or orders still in transit

con.execute("""
    CREATE OR REPLACE VIEW delivered_orders AS
    SELECT
        o.order_id,
        o.customer_id,
        o.order_purchase_timestamp::TIMESTAMP AS order_date,
        o.order_delivered_customer_date::TIMESTAMP AS delivery_date,
        c.customer_unique_id,
        c.customer_state
    FROM orders o
    JOIN customers c ON o.customer_id = c.customer_id
    WHERE o.order_status = 'delivered'
      AND o.order_purchase_timestamp IS NOT NULL
      AND o.order_delivered_customer_date IS NOT NULL
""")

print("Delivered orders:", con.execute("SELECT COUNT(*) FROM delivered_orders").fetchone()[0])

# ============================================================
# CELL 5: Build revenue table
# ============================================================

# Some orders have multiple payment records (split payments)
# Summing by order_id gives the correct total per order

con.execute("""
    CREATE OR REPLACE VIEW order_revenue AS
    SELECT order_id, SUM(payment_value) AS total_revenue
    FROM payments
    GROUP BY order_id
""")

con.execute("""
    CREATE OR REPLACE VIEW orders_with_revenue AS
    SELECT d.*, r.total_revenue
    FROM delivered_orders d
    LEFT JOIN order_revenue r ON d.order_id = r.order_id
    WHERE r.total_revenue IS NOT NULL
      AND r.total_revenue > 0
""")

print("Orders with revenue:", con.execute("SELECT COUNT(*) FROM orders_with_revenue").fetchone()[0])

# ============================================================
# CELL 6: Star schema tables
# ============================================================

fact_orders = con.execute("""
    SELECT
        order_id,
        customer_unique_id,
        customer_state,
        order_date,
        delivery_date,
        total_revenue,
        DATE_TRUNC('month', order_date) AS order_month,
        YEAR(order_date) AS order_year
    FROM orders_with_revenue
    ORDER BY order_date
""").df()

dim_customer = con.execute("""
    SELECT
        customer_unique_id,
        MIN(order_date)        AS first_order_date,
        COUNT(DISTINCT order_id) AS total_orders,
        SUM(total_revenue)     AS lifetime_revenue
    FROM orders_with_revenue
    GROUP BY customer_unique_id
""").df()

dim_monthly_revenue = con.execute("""
    SELECT
        DATE_TRUNC('month', order_date)    AS month,
        COUNT(DISTINCT order_id)           AS order_count,
        COUNT(DISTINCT customer_unique_id) AS unique_customers,
        ROUND(SUM(total_revenue), 2)       AS total_revenue,
        ROUND(AVG(total_revenue), 2)       AS avg_order_value
    FROM orders_with_revenue
    GROUP BY DATE_TRUNC('month', order_date)
    ORDER BY month
""").df()

dim_state_revenue = con.execute("""
    SELECT
        customer_state,
        COUNT(DISTINCT order_id)           AS order_count,
        COUNT(DISTINCT customer_unique_id) AS unique_customers,
        ROUND(SUM(total_revenue), 2)       AS total_revenue
    FROM orders_with_revenue
    GROUP BY customer_state
    ORDER BY total_revenue DESC
""").df()

print(f"Fact orders:   {len(fact_orders):,} rows")
print(f"Dim customers: {len(dim_customer):,} rows")

# ============================================================
# CELL 7: Cohort classification
# ============================================================

con.execute("""
    CREATE OR REPLACE TABLE cohort_base AS
    SELECT
        o.order_id,
        o.customer_unique_id,
        o.order_date,
        o.total_revenue,
        c.first_order_date,
        DATEDIFF('day', c.first_order_date, o.order_date) AS days_since_first_order,
        CASE
            WHEN DATEDIFF('day', c.first_order_date, o.order_date) = 0
            THEN 'New Customer'
            ELSE 'Returning Customer'
        END AS customer_type
    FROM orders_with_revenue o
    JOIN (
        SELECT customer_unique_id, MIN(order_date) AS first_order_date
        FROM orders_with_revenue
        GROUP BY customer_unique_id
    ) c ON o.customer_unique_id = c.customer_unique_id
""")

print(con.execute("""
    SELECT customer_type, COUNT(*) AS orders, ROUND(SUM(total_revenue), 2) AS revenue
    FROM cohort_base
    GROUP BY customer_type
""").df())

# ============================================================
# CELL 8: Retention rates (30/60/90 day)
# ============================================================

retention = con.execute("""
    WITH new_customers AS (
        SELECT DISTINCT customer_unique_id, first_order_date
        FROM cohort_base
        WHERE customer_type = 'New Customer'
    ),
    repeat_orders AS (
        SELECT
            n.customer_unique_id,
            n.first_order_date,
            DATEDIFF('day', n.first_order_date, MIN(o.order_date)) AS days_to_return
        FROM new_customers n
        JOIN orders_with_revenue o
            ON n.customer_unique_id = o.customer_unique_id
            AND o.order_date > n.first_order_date
        GROUP BY n.customer_unique_id, n.first_order_date
    )
    SELECT
        COUNT(DISTINCT n.customer_unique_id) AS total_new_customers,
        COUNT(DISTINCT CASE WHEN r.days_to_return <= 30 THEN r.customer_unique_id END) AS returned_30d,
        COUNT(DISTINCT CASE WHEN r.days_to_return <= 60 THEN r.customer_unique_id END) AS returned_60d,
        COUNT(DISTINCT CASE WHEN r.days_to_return <= 90 THEN r.customer_unique_id END) AS returned_90d,
        ROUND(COUNT(DISTINCT CASE WHEN r.days_to_return <= 30 THEN r.customer_unique_id END) * 100.0
            / COUNT(DISTINCT n.customer_unique_id), 2) AS retention_rate_30d,
        ROUND(COUNT(DISTINCT CASE WHEN r.days_to_return <= 60 THEN r.customer_unique_id END) * 100.0
            / COUNT(DISTINCT n.customer_unique_id), 2) AS retention_rate_60d,
        ROUND(COUNT(DISTINCT CASE WHEN r.days_to_return <= 90 THEN r.customer_unique_id END) * 100.0
            / COUNT(DISTINCT n.customer_unique_id), 2) AS retention_rate_90d
    FROM new_customers n
    LEFT JOIN repeat_orders r ON n.customer_unique_id = r.customer_unique_id
""").df()

print("Retention rates:")
print(retention)

# ============================================================
# CELL 9: Return timing buckets
# ============================================================

churn_buckets = con.execute("""
    WITH new_customers AS (
        SELECT DISTINCT customer_unique_id, first_order_date
        FROM cohort_base
        WHERE customer_type = 'New Customer'
    ),
    repeat_orders AS (
        SELECT
            n.customer_unique_id,
            DATEDIFF('day', n.first_order_date, MIN(o.order_date)) AS days_to_return
        FROM new_customers n
        JOIN orders_with_revenue o
            ON n.customer_unique_id = o.customer_unique_id
            AND o.order_date > n.first_order_date
        GROUP BY n.customer_unique_id, n.first_order_date
    )
    SELECT
        CASE
            WHEN r.days_to_return IS NULL   THEN 'Never returned'
            WHEN r.days_to_return <= 30     THEN '0-30 days'
            WHEN r.days_to_return <= 60     THEN '31-60 days'
            WHEN r.days_to_return <= 90     THEN '61-90 days'
            WHEN r.days_to_return <= 180    THEN '91-180 days'
            ELSE '180+ days'
        END AS return_bucket,
        COUNT(*) AS customer_count
    FROM new_customers n
    LEFT JOIN repeat_orders r ON n.customer_unique_id = r.customer_unique_id
    GROUP BY return_bucket
    ORDER BY customer_count DESC
""").df()

print("Return timing:")
print(churn_buckets)

# ============================================================
# CELL 10: Revenue by customer segment
# ============================================================

segment_revenue = con.execute("""
    SELECT
        customer_type,
        COUNT(DISTINCT customer_unique_id)                                   AS unique_customers,
        COUNT(order_id)                                                      AS total_orders,
        ROUND(SUM(total_revenue), 2)                                         AS total_revenue,
        ROUND(AVG(total_revenue), 2)                                         AS avg_order_value,
        ROUND(SUM(total_revenue) / COUNT(DISTINCT customer_unique_id), 2)   AS revenue_per_customer
    FROM cohort_base
    GROUP BY customer_type
""").df()

print("Revenue by segment:")
print(segment_revenue)

# ============================================================
# CELL 11: Charts (2x2 grid, all variables defined here)
# ============================================================

bucket_order = ['0-30 days', '31-60 days', '61-90 days', '91-180 days', '180+ days']

fig, axes = plt.subplots(2, 2, figsize=(16, 12))
fig.suptitle('Customer Revenue & Retention Analysis — Olist E-Commerce',
             fontsize=14, fontweight='bold')
plt.subplots_adjust(top=0.93)

# Chart 1: Retention rates
ax1 = axes[0, 0]
periods = ['30 Days', '60 Days', '90 Days']
rates = [
    float(retention['retention_rate_30d'].iloc[0]),
    float(retention['retention_rate_60d'].iloc[0]),
    float(retention['retention_rate_90d'].iloc[0])
]
bars1 = ax1.bar(periods, rates, color=['#2C7BB6', '#1A9641', '#D7191C'])
ax1.set_title('Customer Retention Rates', fontweight='bold')
ax1.set_ylabel('Retention Rate (%)')
ax1.set_ylim(0, max(rates) * 1.4)
for bar, rate in zip(bars1, rates):
    ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.02,
             f'{rate}%', ha='center', va='bottom', fontweight='bold')

# Chart 2: Return timing (sorted chronologically)
ax2 = axes[0, 1]
buckets_plot = churn_buckets[churn_buckets['return_bucket'] != 'Never returned'].copy()
buckets_plot['return_bucket'] = pd.Categorical(
    buckets_plot['return_bucket'], categories=bucket_order, ordered=True)
buckets_plot = buckets_plot.sort_values('return_bucket')
ax2.bar(buckets_plot['return_bucket'], buckets_plot['customer_count'], color='#2C7BB6')
ax2.set_title('When Customers Return (Those Who Do)', fontweight='bold')
ax2.set_ylabel('Number of Customers')
ax2.tick_params(axis='x', rotation=30)

# Chart 3: Revenue by customer type
ax3 = axes[1, 0]
seg_sorted = segment_revenue.sort_values('total_revenue', ascending=False)
colors3 = ['#2C7BB6' if t == 'New Customer' else '#D7191C'
           for t in seg_sorted['customer_type']]
bars3 = ax3.bar(seg_sorted['customer_type'], seg_sorted['total_revenue'], color=colors3)
ax3.set_title('Total Revenue by Customer Type', fontweight='bold')
ax3.set_ylabel('Total Revenue (BRL)')
ax3.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, p: f'R${x/1e6:.1f}M'))
for bar, val in zip(bars3, seg_sorted['total_revenue']):
    ax3.text(bar.get_x() + bar.get_width()/2, bar.get_height() * 0.95,
             f'R${val/1e6:.1f}M', ha='center', va='top',
             fontweight='bold', color='white', fontsize=11)

# Chart 4: Monthly revenue trend
ax4 = axes[1, 1]
monthly = dim_monthly_revenue.copy()
monthly['month'] = pd.to_datetime(monthly['month'])
ax4.plot(monthly['month'], monthly['total_revenue'],
         color='#2C7BB6', linewidth=2, marker='o', markersize=4)
ax4.fill_between(monthly['month'], monthly['total_revenue'],
                 alpha=0.15, color='#2C7BB6')
ax4.set_title('Monthly Revenue Trend', fontweight='bold')
ax4.set_xlabel('Month')
ax4.set_ylabel('Total Revenue (BRL)')
ax4.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, p: f'R${x:,.0f}'))

plt.tight_layout()
plt.savefig('retention_analysis.png', dpi=150, bbox_inches='tight')
plt.show()
print("Chart saved.")

# ============================================================
# CELL 12: Export CSVs
# ============================================================

cohort_df = con.execute("SELECT * FROM cohort_base").df()

fact_orders.to_csv('fact_orders.csv', index=False)
dim_customer.to_csv('dim_customer.csv', index=False)
dim_monthly_revenue.to_csv('dim_monthly_revenue.csv', index=False)
dim_state_revenue.to_csv('dim_state_revenue.csv', index=False)
cohort_df.to_csv('cohort_analysis.csv', index=False)
churn_buckets.to_csv('churn_buckets.csv', index=False)
retention.to_csv('retention_rates.csv', index=False)
segment_revenue.to_csv('segment_revenue.csv', index=False)

print("All files saved.")

# ============================================================
# CELL 13: Download (Colab only)
# ============================================================

from google.colab import files
import os

export_files = [
    'fact_orders.csv',
    'dim_customer.csv',
    'dim_monthly_revenue.csv',
    'dim_state_revenue.csv',
    'cohort_analysis.csv',
    'churn_buckets.csv',
    'retention_rates.csv',
    'segment_revenue.csv',
    'retention_analysis.png'
]

for f in export_files:
    if os.path.exists(f):
        files.download(f)
        print(f"Downloaded: {f}")
    else:
        print(f"Not found: {f}")